export type Quote = {
  text: string;
  author: string;
};

// Starter pool. Aim for 60-220 chars, single-sentence preferred.
// Add more here freely — the daily index is taken modulo the array length,
// so growing the list just means new variety. Avoid characters that don't
// render as letters/standard punctuation.
export const quotes: Quote[] = [
  { text: "I take the view and always have that if you cannot say what you are going to say in twenty minutes you ought to go away and write a book about it.", author: "Lord Brabazon" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", author: "Mark Twain" },
  { text: "Kindness is the language which the deaf can hear and the blind can see.", author: "Mark Twain" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
  { text: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", author: "Mark Twain" },
  { text: "Continuous effort, not strength or intelligence, is the key to unlocking our potential.", author: "Winston Churchill" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "We make a living by what we get. We make a life by what we give.", author: "Winston Churchill" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill" },
  { text: "If you are going through hell, keep going.", author: "Winston Churchill" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { text: "I can resist everything except temptation.", author: "Oscar Wilde" },
  { text: "Experience is simply the name we give our mistakes.", author: "Oscar Wilde" },
  { text: "Folks are usually about as happy as they make their minds up to be.", author: "Abraham Lincoln" },
  { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { text: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
  { text: "Nearly all men can stand adversity, but if you want to test a man's character, give him power.", author: "Abraham Lincoln" },
  { text: "I am a slow walker, but I never walk back.", author: "Abraham Lincoln" },
  { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "Lost time is never found again.", author: "Benjamin Franklin" },
  { text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin" },
  { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Comparison is the thief of joy.", author: "Theodore Roosevelt" },
  { text: "Nothing in the world is worth having or worth doing unless it means effort, pain, difficulty.", author: "Theodore Roosevelt" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Once you make a decision, the universe conspires to make it happen.", author: "Ralph Waldo Emerson" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
  { text: "It is not what you look at that matters, it is what you see.", author: "Henry David Thoreau" },
  { text: "The cost of a thing is the amount of life you exchange for it.", author: "Henry David Thoreau" },
  { text: "Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.", author: "Robert Frost" },
  { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
  { text: "The best way out is always through.", author: "Robert Frost" },
  { text: "I have learned that people will forget what you said, but they will never forget how you made them feel.", author: "Maya Angelou" },
  { text: "If you don't like something, change it. If you can't change it, change your attitude.", author: "Maya Angelou" },
  { text: "Try to be a rainbow in someone's cloud.", author: "Maya Angelou" },
  { text: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
  { text: "You may encounter many defeats, but you must not be defeated.", author: "Maya Angelou" },
  { text: "You must do the things you think you cannot do.", author: "Eleanor Roosevelt" },
  { text: "Courage is grace under pressure.", author: "Ernest Hemingway" },
  { text: "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.", author: "Ernest Hemingway" },
  { text: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", author: "Albus Dumbledore" },
  { text: "It is our choices that show what we truly are, far more than our abilities.", author: "Albus Dumbledore" },
  { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { text: "Even the smallest person can change the course of the future.", author: "J.R.R. Tolkien" },
  { text: "All we have to decide is what to do with the time that is given us.", author: "J.R.R. Tolkien" },
  { text: "Courage is found in unlikely places.", author: "J.R.R. Tolkien" },
  { text: "You can't go back and change the beginning, but you can start where you are and change the ending.", author: "C.S. Lewis" },
  { text: "Integrity is doing the right thing, even when no one is watching.", author: "C.S. Lewis" },
  { text: "We are what we believe we are.", author: "C.S. Lewis" },
  { text: "There are far better things ahead than any we leave behind.", author: "C.S. Lewis" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu" },
  { text: "Knowing others is intelligence; knowing yourself is true wisdom.", author: "Lao Tzu" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius" },
  { text: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "He who knows others is wise; he who knows himself is enlightened.", author: "Confucius" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Will Durant" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle" },
  { text: "The whole is greater than the sum of its parts.", author: "Aristotle" },
  { text: "An unexamined life is not worth living.", author: "Socrates" },
  { text: "I know that I know nothing.", author: "Socrates" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "Wonder is the beginning of wisdom.", author: "Socrates" },
  { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "What we do now echoes in eternity.", author: "Marcus Aurelius" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "Every new beginning comes from some other beginning's end.", author: "Seneca" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca" },
  { text: "It is not what happens to you, but how you react to it that matters.", author: "Epictetus" },
  { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "I learned that courage was not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", author: "Martin Luther King Jr." },
  { text: "The time is always right to do what is right.", author: "Martin Luther King Jr." },
  { text: "Faith is taking the first step even when you don't see the whole staircase.", author: "Martin Luther King Jr." },
  { text: "We may have all come on different ships, but we're in the same boat now.", author: "Martin Luther King Jr." },
  { text: "Whoever is happy will make others happy too.", author: "Anne Frank" },
  { text: "Think before you act.", author: "Anne Frank" },
  { text: "No one has ever become poor by giving.", author: "Anne Frank" },
  { text: "I don't think of all the misery, but of the beauty that still remains.", author: "Anne Frank" },
  { text: "If there is no struggle, there is no progress.", author: "Frederick Douglass" },
  { text: "It is easier to build strong children than to repair broken men.", author: "Frederick Douglass" },
  { text: "Once you learn to read, you will be forever free.", author: "Frederick Douglass" },
  { text: "Ask not what your country can do for you, ask what you can do for your country.", author: "John F. Kennedy" },
  { text: "We choose to go to the moon not because it is easy, but because it is hard.", author: "John F. Kennedy" },
  { text: "Change is the law of life. And those who look only to the past or present are certain to miss the future.", author: "John F. Kennedy" },
  { text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Bruce Lee" },
  { text: "If you spend too much time thinking about a thing, you'll never get it done.", author: "Bruce Lee" },
  { text: "Mistakes are always forgivable, if one has the courage to admit them.", author: "Bruce Lee" },
  { text: "When the whole world is silent, even one voice becomes powerful.", author: "Malala Yousafzai" },
  { text: "I raise up my voice not so I can shout, but so that those without a voice can be heard.", author: "Malala Yousafzai" },
  { text: "Stay close to anything that makes you glad you are alive.", author: "Hafiz" },
  { text: "The wound is the place where the light enters you.", author: "Rumi" },
  { text: "What you seek is seeking you.", author: "Rumi" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi" },
  { text: "Try to be like the turtle — at ease in your own shell.", author: "Bill Copeland" },
  { text: "Life is what happens to you while you're busy making other plans.", author: "John Lennon" },
  { text: "Do what you feel in your heart to be right, for you'll be criticized anyway.", author: "Eleanor Roosevelt" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Learn from yesterday, live for today, hope for tomorrow.", author: "Albert Einstein" },
  { text: "If you can dream it, you can do it.", author: "Walt Disney" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney" },
  { text: "Don't cry because it's over, smile because it happened.", author: "Dr. Seuss" },
  { text: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", author: "Dr. Seuss" },
  { text: "Today you are you, that is truer than true. There is no one alive who is youer than you.", author: "Dr. Seuss" },
  { text: "Why fit in when you were born to stand out?", author: "Dr. Seuss" },
  { text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk" },
  { text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt" },
  { text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { text: "We cannot always build the future for our youth, but we can build our youth for the future.", author: "Franklin D. Roosevelt" },
  { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
  { text: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { text: "I have not failed. I've just found ten thousand ways that won't work.", author: "Thomas Edison" },
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "Hope is being able to see that there is light despite all of the darkness.", author: "Desmond Tutu" },
  { text: "Do your little bit of good where you are; it's those little bits of good put together that overwhelm the world.", author: "Desmond Tutu" },
  { text: "There is more treasure in books than in all the pirate's loot on Treasure Island.", author: "Walt Disney" },
  { text: "Books are a uniquely portable magic.", author: "Stephen King" },
  { text: "A reader lives a thousand lives before he dies. The man who never reads lives only one.", author: "George R.R. Martin" },
  { text: "The man who does not read has no advantage over the man who cannot read.", author: "Mark Twain" },
  { text: "There is no friend as loyal as a book.", author: "Ernest Hemingway" },
  { text: "Always do what is right. It will gratify half of mankind and astound the other.", author: "Mark Twain" },
  { text: "Don't go around saying the world owes you a living. The world owes you nothing. It was here first.", author: "Mark Twain" },
  { text: "When in doubt, tell the truth.", author: "Mark Twain" },
  { text: "I have never let my schooling interfere with my education.", author: "Mark Twain" },
  { text: "Wrinkles should merely indicate where smiles have been.", author: "Mark Twain" },
  { text: "Travel is fatal to prejudice, bigotry, and narrow-mindedness.", author: "Mark Twain" },
  { text: "Never put off till tomorrow what may be done day after tomorrow just as well.", author: "Mark Twain" },
  { text: "Get your facts first, then you can distort them as you please.", author: "Mark Twain" },
  { text: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
  { text: "Anger is an acid that can do more harm to the vessel in which it is stored than to anything on which it is poured.", author: "Mark Twain" },
  { text: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain" },
  { text: "It's not the size of the dog in the fight, it's the size of the fight in the dog.", author: "Mark Twain" },
  { text: "Forgiveness is the fragrance that the violet sheds on the heel that has crushed it.", author: "Mark Twain" },
  { text: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde" },
  { text: "Some cause happiness wherever they go; others whenever they go.", author: "Oscar Wilde" },
  { text: "I am not young enough to know everything.", author: "Oscar Wilde" },
  { text: "The truth is rarely pure and never simple.", author: "Oscar Wilde" },
  { text: "A gentleman is one who never hurts anyone's feelings unintentionally.", author: "Oscar Wilde" },
  { text: "Anyone who lives within their means suffers from a lack of imagination.", author: "Oscar Wilde" },
  { text: "The best way to make children good is to make them happy.", author: "Oscar Wilde" },
  { text: "Education is an admirable thing, but it is well to remember that nothing that is worth knowing can be taught.", author: "Oscar Wilde" },
  { text: "It is absurd to divide people into good and bad. People are either charming or tedious.", author: "Oscar Wilde" },
  { text: "There is no sin except stupidity.", author: "Oscar Wilde" },
  { text: "Never give in, never, never, never, never.", author: "Winston Churchill" },
  { text: "Success is stumbling from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { text: "An optimist sees the opportunity in every difficulty; a pessimist sees the difficulty in every opportunity.", author: "Winston Churchill" },
  { text: "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.", author: "Winston Churchill" },
  { text: "Without courage, all other virtues lose their meaning.", author: "Winston Churchill" },
  { text: "We shape our buildings; thereafter they shape us.", author: "Winston Churchill" },
  { text: "History will be kind to me, for I intend to write it.", author: "Winston Churchill" },
  { text: "The price of greatness is responsibility.", author: "Winston Churchill" },
  { text: "I never worry about action, but only about inaction.", author: "Winston Churchill" },
  { text: "The empires of the future are the empires of the mind.", author: "Winston Churchill" },
  { text: "And in the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
  { text: "I will prepare and some day my chance will come.", author: "Abraham Lincoln" },
  { text: "You cannot escape the responsibility of tomorrow by evading it today.", author: "Abraham Lincoln" },
  { text: "Always bear in mind that your own resolution to succeed is more important than any other one thing.", author: "Abraham Lincoln" },
  { text: "Truth is generally the best vindication against slander.", author: "Abraham Lincoln" },
  { text: "Early to bed and early to rise makes a man healthy, wealthy, and wise.", author: "Benjamin Franklin" },
  { text: "He that can have patience can have what he will.", author: "Benjamin Franklin" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "A penny saved is a penny earned.", author: "Benjamin Franklin" },
  { text: "If you would not be forgotten as soon as you are dead and rotten, either write things worth reading, or do things worth the writing.", author: "Benjamin Franklin" },
  { text: "Honesty is the best policy.", author: "Benjamin Franklin" },
  { text: "Genius without education is like silver in the mine.", author: "Benjamin Franklin" },
  { text: "Time is money.", author: "Benjamin Franklin" },
  { text: "Only a life lived for others is a life worthwhile.", author: "Albert Einstein" },
  { text: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", author: "Albert Einstein" },
  { text: "Logic will get you from A to Z; imagination will get you everywhere.", author: "Albert Einstein" },
  { text: "Look deep into nature, and then you will understand everything better.", author: "Albert Einstein" },
  { text: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein" },
  { text: "If you can't explain it simply, you don't understand it well enough.", author: "Albert Einstein" },
  { text: "Peace cannot be kept by force; it can only be achieved by understanding.", author: "Albert Einstein" },
  { text: "Education is what remains after one has forgotten what one has learned in school.", author: "Albert Einstein" },
  { text: "Sometimes life hits you in the head with a brick. Don't lose faith.", author: "Steve Jobs" },
  { text: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Steve Jobs" },
  { text: "Quality is more important than quantity. One home run is much better than two doubles.", author: "Steve Jobs" },
  { text: "Things don't have to change the world to be important.", author: "Steve Jobs" },
  { text: "Far and away the best prize that life has to offer is the chance to work hard at work worth doing.", author: "Theodore Roosevelt" },
  { text: "It is hard to fail, but it is worse never to have tried to succeed.", author: "Theodore Roosevelt" },
  { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
  { text: "The only man who never makes mistakes is the man who never does anything.", author: "Theodore Roosevelt" },
  { text: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt" },
  { text: "Learn from the mistakes of others. You can't live long enough to make them all yourself.", author: "Eleanor Roosevelt" },
  { text: "When life is too easy for us, we must beware or we may not be ready to meet the blows which sooner or later come to everyone.", author: "Eleanor Roosevelt" },
  { text: "A woman is like a tea bag; you never know how strong she is until she gets in hot water.", author: "Eleanor Roosevelt" },
  { text: "The best and most beautiful things in the world cannot be seen or even touched, they must be felt with the heart.", author: "Helen Keller" },
  { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
  { text: "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", author: "Helen Keller" },
  { text: "Although the world is full of suffering, it is also full of the overcoming of it.", author: "Helen Keller" },
  { text: "Keep your face to the sunshine and you cannot see a shadow.", author: "Helen Keller" },
  { text: "Alone we can do so little; together we can do so much.", author: "Helen Keller" },
  { text: "Walking with a friend in the dark is better than walking alone in the light.", author: "Helen Keller" },
  { text: "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.", author: "Helen Keller" },
  { text: "I am only one, but still I am one. I cannot do everything, but still I can do something.", author: "Helen Keller" },
  { text: "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.", author: "Helen Keller" },
  { text: "Things do not change; we change.", author: "Henry David Thoreau" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "If you have built castles in the air, your work need not be lost; that is where they should be. Now put the foundations under them.", author: "Henry David Thoreau" },
  { text: "Be true to your work, your word, and your friend.", author: "Henry David Thoreau" },
  { text: "Aim above morality. Be not simply good; be good for something.", author: "Henry David Thoreau" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "For every minute you are angry you lose sixty seconds of happiness.", author: "Ralph Waldo Emerson" },
  { text: "Finish each day and be done with it. You have done what you could.", author: "Ralph Waldo Emerson" },
  { text: "Make the most of yourself, for that is all there is of you.", author: "Ralph Waldo Emerson" },
  { text: "Trust thyself: every heart vibrates to that iron string.", author: "Ralph Waldo Emerson" },
  { text: "Without ambition one starts nothing. Without work one finishes nothing.", author: "Ralph Waldo Emerson" },
  { text: "Write it on your heart that every day is the best day in the year.", author: "Ralph Waldo Emerson" },
  { text: "Adopt the pace of nature: her secret is patience.", author: "Ralph Waldo Emerson" },
  { text: "Don't ever take a fence down until you know the reason it was put up.", author: "Robert Frost" },
  { text: "I am not a teacher, but an awakener.", author: "Robert Frost" },
  { text: "A poem begins as a lump in the throat, a sense of wrong, a homesickness, a lovesickness.", author: "Robert Frost" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.", author: "Maya Angelou" },
  { text: "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.", author: "Maya Angelou" },
  { text: "If you must look back, do so forgivingly. If you must look forward, do so prayerfully.", author: "Maya Angelou" },
  { text: "Friendship is born at that moment when one person says to another: What! You too? I thought I was the only one.", author: "C.S. Lewis" },
  { text: "The task of the modern educator is not to cut down jungles, but to irrigate deserts.", author: "C.S. Lewis" },
  { text: "Don't let your happiness depend on something you may lose.", author: "C.S. Lewis" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { text: "Aim at heaven and you will get earth thrown in. Aim at earth and you get neither.", author: "C.S. Lewis" },
  { text: "Wherever you go, go with all your heart.", author: "Confucius" },
  { text: "When it is obvious that the goals cannot be reached, don't adjust the goals, adjust the action steps.", author: "Confucius" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
  { text: "Silence is a true friend who never betrays.", author: "Confucius" },
  { text: "Music in the soul can be heard by the universe.", author: "Lao Tzu" },
  { text: "A good traveler has no fixed plans and is not intent on arriving.", author: "Lao Tzu" },
  { text: "If you do not change direction, you may end up where you are heading.", author: "Lao Tzu" },
  { text: "Mastering others is strength. Mastering yourself is true power.", author: "Lao Tzu" },
  { text: "Be content with what you have; rejoice in the way things are. When you realize there is nothing lacking, the whole world belongs to you.", author: "Lao Tzu" },
  { text: "Pleasure in the job puts perfection in the work.", author: "Aristotle" },
  { text: "Educating the mind without educating the heart is no education at all.", author: "Aristotle" },
  { text: "He who has overcome his fears will truly be free.", author: "Aristotle" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { text: "Hope is a waking dream.", author: "Aristotle" },
  { text: "He who is not contented with what he has, would not be contented with what he would like to have.", author: "Socrates" },
  { text: "Education is the kindling of a flame, not the filling of a vessel.", author: "Socrates" },
  { text: "The secret of happiness is not found in seeking more, but in developing the capacity to enjoy less.", author: "Socrates" },
  { text: "Good people do not need laws to tell them to act responsibly, while bad people will find a way around the laws.", author: "Plato" },
  { text: "Wise men speak because they have something to say; fools because they have to say something.", author: "Plato" },
  { text: "The price good men pay for indifference to public affairs is to be ruled by evil men.", author: "Plato" },
  { text: "Music gives a soul to the universe, wings to the mind, flight to the imagination, and life to everything.", author: "Plato" },
  { text: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", author: "Plato" },
  { text: "Be kind, for everyone you meet is fighting a hard battle.", author: "Plato" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
  { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together.", author: "Marcus Aurelius" },
  { text: "The best revenge is to be unlike him who performed the injury.", author: "Marcus Aurelius" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive: to breathe, to think, to enjoy, to love.", author: "Marcus Aurelius" },
  { text: "If a man knows not to which port he sails, no wind is favorable.", author: "Seneca" },
  { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca" },
  { text: "Sometimes even to live is an act of courage.", author: "Seneca" },
  { text: "He suffers more than necessary, who suffers before it is necessary.", author: "Seneca" },
  { text: "While we are postponing, life speeds by.", author: "Seneca" },
  { text: "Don't explain your philosophy. Embody it.", author: "Epictetus" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus" },
  { text: "Only the educated are free.", author: "Epictetus" },
  { text: "He who laughs at himself never runs out of things to laugh at.", author: "Epictetus" },
  { text: "The greater the difficulty, the more glory in surmounting it.", author: "Epictetus" },
  { text: "An eye for an eye will only make the whole world blind.", author: "Mahatma Gandhi" },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
  { text: "There is no passion to be found playing small, in settling for a life that is less than the one you are capable of living.", author: "Nelson Mandela" },
  { text: "After climbing a great hill, one only finds that there are many more hills to climb.", author: "Nelson Mandela" },
  { text: "Resentment is like drinking poison and then hoping it will kill your enemies.", author: "Nelson Mandela" },
  { text: "If you talk to a man in a language he understands, that goes to his head. If you talk to him in his own language, that goes to his heart.", author: "Nelson Mandela" },
  { text: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr." },
  { text: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr." },
  { text: "Returning hate for hate multiplies hate.", author: "Martin Luther King Jr." },
  { text: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", author: "Martin Luther King Jr." },
  { text: "We must accept finite disappointment, but never lose infinite hope.", author: "Martin Luther King Jr." },
  { text: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author: "Anne Frank" },
  { text: "In spite of everything, I still believe that people are really good at heart.", author: "Anne Frank" },
  { text: "Look at how a single candle can both defy and define the darkness.", author: "Anne Frank" },
  { text: "I prefer to be true to myself, even at the hazard of incurring the ridicule of others, rather than to be false.", author: "Frederick Douglass" },
  { text: "Things do not happen. Things are made to happen.", author: "John F. Kennedy" },
  { text: "Forgive your enemies, but never forget their names.", author: "John F. Kennedy" },
  { text: "A man may die, nations may rise and fall, but an idea lives on.", author: "John F. Kennedy" },
  { text: "Whether you think you can, or you think you can't, you're right.", author: "Henry Ford" },
  { text: "Coming together is a beginning; keeping together is progress; working together is success.", author: "Henry Ford" },
  { text: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford" },
  { text: "Quality means doing it right when no one is looking.", author: "Henry Ford" },
  { text: "Anyone who stops learning is old, whether at twenty or eighty.", author: "Henry Ford" },
  { text: "There is no substitute for hard work.", author: "Thomas Edison" },
  { text: "Just because something doesn't do what you planned it to do doesn't mean it's useless.", author: "Thomas Edison" },
  { text: "If we did all the things we are capable of, we would astound ourselves.", author: "Thomas Edison" },
  { text: "Be like water making its way through cracks. Do not be assertive, but adjust to the object.", author: "Bruce Lee" },
  { text: "A wise man can learn more from a foolish question than a fool can learn from a wise answer.", author: "Bruce Lee" },
  { text: "I fear not the man who has practiced ten thousand kicks once, but I fear the man who has practiced one kick ten thousand times.", author: "Bruce Lee" },
  { text: "Sometimes you will never know the value of a moment until it becomes a memory.", author: "Dr. Seuss" },
  { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
  { text: "Today is your day! Your mountain is waiting. So get on your way.", author: "Dr. Seuss" },
  { text: "Unless someone like you cares a whole awful lot, nothing is going to get better. It's not.", author: "Dr. Seuss" },
  { text: "It does not do to dwell on dreams and forget to live.", author: "J.K. Rowling" },
  { text: "Anything's possible if you've got enough nerve.", author: "J.K. Rowling" },
  { text: "I will not say: do not weep; for not all tears are an evil.", author: "J.R.R. Tolkien" },
  { text: "It's a dangerous business, going out your door. You step onto the road, and if you don't keep your feet, there's no knowing where you might be swept off to.", author: "J.R.R. Tolkien" },
  { text: "The world breaks everyone, and afterward, many are strong at the broken places.", author: "Ernest Hemingway" },
  { text: "There is nothing to writing. All you do is sit down at a typewriter and bleed.", author: "Ernest Hemingway" },
  { text: "So we beat on, boats against the current, borne back ceaselessly into the past.", author: "F. Scott Fitzgerald" },
  { text: "Never confuse a single defeat with a final defeat.", author: "F. Scott Fitzgerald" },
  { text: "Show me a hero, and I will write you a tragedy.", author: "F. Scott Fitzgerald" },
  { text: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "We don't stop playing because we grow old; we grow old because we stop playing.", author: "George Bernard Shaw" },
  { text: "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.", author: "George Bernard Shaw" },
  { text: "Beware of false knowledge; it is more dangerous than ignorance.", author: "George Bernard Shaw" },
  { text: "Imagination is the beginning of creation.", author: "George Bernard Shaw" },
  { text: "What do we live for, if it is not to make life less difficult for each other?", author: "George Eliot" },
  { text: "Wear a smile and have friends; wear a scowl and have wrinkles.", author: "George Eliot" },
  { text: "Common sense is not so common.", author: "Voltaire" },
  { text: "Those who can make you believe absurdities can make you commit atrocities.", author: "Voltaire" },
  { text: "Judge a man by his questions rather than by his answers.", author: "Voltaire" },
  { text: "The secret of being a bore is to tell everything.", author: "Voltaire" },
  { text: "Doubt is not a pleasant condition, but certainty is absurd.", author: "Voltaire" },
  { text: "All the world's a stage, and all the men and women merely players.", author: "William Shakespeare" },
  { text: "We know what we are, but know not what we may be.", author: "William Shakespeare" },
  { text: "What's in a name? That which we call a rose by any other name would smell as sweet.", author: "William Shakespeare" },
  { text: "The course of true love never did run smooth.", author: "William Shakespeare" },
  { text: "There is nothing either good or bad, but thinking makes it so.", author: "William Shakespeare" },
  { text: "Cowards die many times before their deaths; the valiant never taste of death but once.", author: "William Shakespeare" },
  { text: "Some are born great, some achieve greatness, and some have greatness thrust upon them.", author: "William Shakespeare" },
  { text: "The fool doth think he is wise, but the wise man knows himself to be a fool.", author: "William Shakespeare" },
  { text: "There is no charm equal to tenderness of heart.", author: "Jane Austen" },
  { text: "Friendship is certainly the finest balm for the pangs of disappointed love.", author: "Jane Austen" },
  { text: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", author: "Jane Austen" },
  { text: "It was the best of times, it was the worst of times.", author: "Charles Dickens" },
  { text: "No one is useless in this world who lightens the burdens of another.", author: "Charles Dickens" },
  { text: "Have a heart that never hardens, a temper that never tires, and a touch that never hurts.", author: "Charles Dickens" },
  { text: "Everyone thinks of changing the world, but no one thinks of changing himself.", author: "Leo Tolstoy" },
  { text: "If you want to be happy, be.", author: "Leo Tolstoy" },
  { text: "All happy families are alike; each unhappy family is unhappy in its own way.", author: "Leo Tolstoy" },
  { text: "The two most powerful warriors are patience and time.", author: "Leo Tolstoy" },
  { text: "The mystery of human existence lies not in just staying alive, but in finding something to live for.", author: "Fyodor Dostoyevsky" },
  { text: "Pain and suffering are always inevitable for a large intelligence and a deep heart.", author: "Fyodor Dostoyevsky" },
  { text: "To live without hope is to cease to live.", author: "Fyodor Dostoyevsky" },
  { text: "Knowledge is of no value unless you put it into practice.", author: "Anton Chekhov" },
  { text: "Don't tell me the moon is shining; show me the glint of light on broken glass.", author: "Anton Chekhov" },
  { text: "It is not the strongest of the species that survives, nor the most intelligent; it is the one most adaptable to change.", author: "Charles Darwin" },
  { text: "A man who dares to waste one hour of time has not discovered the value of life.", author: "Charles Darwin" },
  { text: "All truths are easy to understand once they are discovered; the point is to discover them.", author: "Galileo Galilei" },
  { text: "You cannot teach a man anything; you can only help him discover it in himself.", author: "Galileo Galilei" },
  { text: "If I have seen further than others, it is by standing upon the shoulders of giants.", author: "Isaac Newton" },
  { text: "Tact is the art of making a point without making an enemy.", author: "Isaac Newton" },
  { text: "Nothing in life is to be feared, it is only to be understood.", author: "Marie Curie" },
  { text: "I was taught that the way of progress was neither swift nor easy.", author: "Marie Curie" },
  { text: "Be less curious about people and more curious about ideas.", author: "Marie Curie" },
  { text: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
  { text: "We are made of star-stuff.", author: "Carl Sagan" },
  { text: "For small creatures such as we the vastness is bearable only through love.", author: "Carl Sagan" },
  { text: "Intelligence is the ability to adapt to change.", author: "Stephen Hawking" },
  { text: "Look up at the stars and not down at your feet.", author: "Stephen Hawking" },
  { text: "Quiet people have the loudest minds.", author: "Stephen Hawking" },
  { text: "The present is theirs; the future, for which I really worked, is mine.", author: "Nikola Tesla" },
  { text: "I do not think there is any thrill that can go through the human heart like that felt by the inventor.", author: "Nikola Tesla" },
  { text: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Walt Whitman" },
  { text: "I exist as I am, that is enough.", author: "Walt Whitman" },
  { text: "Be curious, not judgmental.", author: "Walt Whitman" },
  { text: "Hope is the thing with feathers that perches in the soul.", author: "Emily Dickinson" },
  { text: "If I can stop one heart from breaking, I shall not live in vain.", author: "Emily Dickinson" },
  { text: "Forever is composed of nows.", author: "Emily Dickinson" },
  { text: "All that we see or seem is but a dream within a dream.", author: "Edgar Allan Poe" },
  { text: "Words have no power to impress the mind without the exquisite horror of their reality.", author: "Edgar Allan Poe" },
  { text: "In a time of universal deceit, telling the truth is a revolutionary act.", author: "George Orwell" },
  { text: "Happiness can exist only in acceptance.", author: "George Orwell" },
  { text: "There is only one corner of the universe you can be certain of improving, and that's your own self.", author: "Aldous Huxley" },
  { text: "Experience is not what happens to you; it's what you do with what happens to you.", author: "Aldous Huxley" },
  { text: "Most human beings have an almost infinite capacity for taking things for granted.", author: "Aldous Huxley" },
  { text: "After silence, that which comes nearest to expressing the inexpressible is music.", author: "Aldous Huxley" },
  { text: "We are what we pretend to be, so we must be careful about what we pretend to be.", author: "Kurt Vonnegut" },
  { text: "I urge you to please notice when you are happy.", author: "Kurt Vonnegut" },
  { text: "And now that you don't have to be perfect, you can be good.", author: "John Steinbeck" },
  { text: "It's so much darker when a light goes out than it would have been if it had never shone.", author: "John Steinbeck" },
  { text: "If there's a book that you want to read, but it hasn't been written yet, then you must write it.", author: "Toni Morrison" },
  { text: "What's the world for if you can't make it up the way you want it?", author: "Toni Morrison" },
  { text: "You never really understand a person until you consider things from his point of view.", author: "Harper Lee" },
  { text: "The one thing that doesn't abide by majority rule is a person's conscience.", author: "Harper Lee" },
  { text: "Every child is an artist. The problem is how to remain an artist once we grow up.", author: "Pablo Picasso" },
  { text: "Art is the elimination of the unnecessary.", author: "Pablo Picasso" },
  { text: "I would rather die of passion than of boredom.", author: "Vincent van Gogh" },
  { text: "Great things are not done by impulse, but by a series of small things brought together.", author: "Vincent van Gogh" },
  { text: "Normality is a paved road: it's comfortable to walk, but no flowers grow on it.", author: "Vincent van Gogh" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
  { text: "Once you have tasted flight, you will forever walk the earth with your eyes turned skyward.", author: "Leonardo da Vinci" },
  { text: "Time stays long enough for those who use it.", author: "Leonardo da Vinci" },
  { text: "I saw the angel in the marble and carved until I set him free.", author: "Michelangelo" },
  { text: "The greater danger for most of us lies not in setting our aim too high and falling short, but in setting our aim too low and achieving our mark.", author: "Michelangelo" },
  { text: "I am my own muse. I am the subject I know best.", author: "Frida Kahlo" },
  { text: "Feet, what do I need them for if I have wings to fly?", author: "Frida Kahlo" },
  { text: "The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.", author: "Bob Marley" },
  { text: "You never know how strong you are until being strong is your only choice.", author: "Bob Marley" },
  { text: "Love the life you live. Live the life you love.", author: "Bob Marley" },
  { text: "He not busy being born is busy dying.", author: "Bob Dylan" },
  { text: "What's money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.", author: "Bob Dylan" },
  { text: "Love is the answer, and you know that for sure.", author: "John Lennon" },
  { text: "Imagine all the people living life in peace.", author: "John Lennon" },
  { text: "I don't know where I'm going from here, but I promise it won't be boring.", author: "David Bowie" },
  { text: "Tomorrow belongs to those who can hear it coming.", author: "David Bowie" },
  { text: "Music can change the world.", author: "Ludwig van Beethoven" },
  { text: "Music is the mediator between the spiritual and the sensual life.", author: "Ludwig van Beethoven" },
  { text: "The music is not in the notes, but in the silence between.", author: "Wolfgang Amadeus Mozart" },
  { text: "You miss one hundred percent of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "I've missed more than nine thousand shots in my career. I've failed over and over and over again. And that is why I succeed.", author: "Michael Jordan" },
  { text: "I can accept failure, everyone fails at something. But I can't accept not trying.", author: "Michael Jordan" },
  { text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
  { text: "Winners never quit and quitters never win.", author: "Vince Lombardi" },
  { text: "Perfection is not attainable. But if we chase perfection, we can catch excellence.", author: "Vince Lombardi" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "Little things make big things happen.", author: "John Wooden" },
  { text: "Be more concerned with your character than your reputation, because your character is what you really are.", author: "John Wooden" },
  { text: "Talent is God-given. Be humble. Fame is man-given. Be grateful. Conceit is self-given. Be careful.", author: "John Wooden" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "Either you run the day or the day runs you.", author: "Jim Rohn" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Don't wish it were easier; wish you were better.", author: "Jim Rohn" },
  { text: "Time is more valuable than money. You can get more money, but you cannot get more time.", author: "Jim Rohn" },
  { text: "Vulnerability is not winning or losing; it's having the courage to show up and be seen when we have no control over the outcome.", author: "Brene Brown" },
  { text: "Owning our story can be hard but not nearly as difficult as spending our lives running from it.", author: "Brene Brown" },
  { text: "Talk to yourself like you would to someone you love.", author: "Brene Brown" },
  { text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned.", author: "Buddha" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "Our prime purpose in this life is to help others. And if you can't help them, at least don't hurt them.", author: "Dalai Lama" },
  { text: "Be kind whenever possible. It is always possible.", author: "Dalai Lama" },
  { text: "If you want others to be happy, practice compassion. If you want to be happy, practice compassion.", author: "Dalai Lama" },
  { text: "Old friends pass away, new friends appear. It is just like the days. An old day passes, a new day arrives.", author: "Dalai Lama" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa" },
  { text: "Not all of us can do great things. But we can do small things with great love.", author: "Mother Teresa" },
  { text: "Peace begins with a smile.", author: "Mother Teresa" },
  { text: "If you judge people, you have no time to love them.", author: "Mother Teresa" },
  { text: "Kind words can be short and easy to speak, but their echoes are truly endless.", author: "Mother Teresa" },
  { text: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks" },
  { text: "You must never be fearful about what you are doing when it is right.", author: "Rosa Parks" },
  { text: "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.", author: "Booker T. Washington" },
  { text: "Excellence is to do a common thing in an uncommon way.", author: "Booker T. Washington" },
  { text: "Character is power.", author: "Booker T. Washington" },
  { text: "Every great dream begins with a dreamer.", author: "Harriet Tubman" },
  { text: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.", author: "Malcolm X" },
  { text: "A man who stands for nothing will fall for anything.", author: "Malcolm X" },
  { text: "We cannot seek achievement for ourselves and forget about progress and prosperity for our community.", author: "Cesar Chavez" },
  { text: "It is better to offer no excuse than a bad one.", author: "George Washington" },
  { text: "Liberty, when it begins to take root, is a plant of rapid growth.", author: "George Washington" },
  { text: "Discipline is the soul of an army. It makes small numbers formidable.", author: "George Washington" },
  { text: "I cannot live without books.", author: "Thomas Jefferson" },
  { text: "Honesty is the first chapter in the book of wisdom.", author: "Thomas Jefferson" },
  { text: "Whenever you do a thing, act as if all the world were watching.", author: "Thomas Jefferson" },
  { text: "Do you want to know who you are? Don't ask. Act! Action will delineate and define you.", author: "Thomas Jefferson" },
  { text: "Facts are stubborn things; and whatever may be our wishes, our inclinations, or the dictates of our passions, they cannot alter the state of facts and evidence.", author: "John Adams" },
  { text: "Liberty cannot be preserved without a general knowledge among the people.", author: "John Adams" },
  { text: "Knowledge will forever govern ignorance, and a people who mean to be their own governors must arm themselves with the power knowledge gives.", author: "James Madison" },
  { text: "Give me liberty, or give me death!", author: "Patrick Henry" },
  { text: "These are the times that try men's souls.", author: "Thomas Paine" },
  { text: "Lead, follow, or get out of the way.", author: "Thomas Paine" },
  { text: "There is no limit to the amount of good you can do if you don't care who gets the credit.", author: "Ronald Reagan" },
  { text: "Trust, but verify.", author: "Ronald Reagan" },
  { text: "When you come to a fork in the road, take it.", author: "Yogi Berra" },
  { text: "It ain't over till it's over.", author: "Yogi Berra" },
  { text: "You can observe a lot just by watching.", author: "Yogi Berra" },
  { text: "It's tough to make predictions, especially about the future.", author: "Yogi Berra" },
  { text: "If you don't know where you are going, you'll end up someplace else.", author: "Yogi Berra" },
  { text: "Even if you're on the right track, you'll get run over if you just sit there.", author: "Will Rogers" },
  { text: "Worrying is like paying a debt you don't owe.", author: "Will Rogers" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { text: "Live in such a way that you would not be ashamed to sell your parrot to the town gossip.", author: "Will Rogers" },
  { text: "Good judgment comes from experience, and a lot of that comes from bad judgment.", author: "Will Rogers" },
  { text: "If you find yourself in a hole, stop digging.", author: "Will Rogers" },
  { text: "The greatest good you can do for another is not just to share your riches but to reveal to him his own.", author: "Benjamin Disraeli" },
  { text: "Action may not always bring happiness, but there is no happiness without action.", author: "Benjamin Disraeli" },
  { text: "Don't follow the crowd, let the crowd follow you.", author: "Margaret Thatcher" },
  { text: "Plan your work for today and every day, then work your plan.", author: "Margaret Thatcher" },
  { text: "There are two kinds of people: those who do the work and those who take the credit. Try to be in the first group, there is less competition there.", author: "Indira Gandhi" },
  { text: "I have the heart and stomach of a king, and of a king of England too.", author: "Queen Elizabeth I" },
  { text: "Grief is the price we pay for love.", author: "Queen Elizabeth II" },
  { text: "I am not afraid; I was born to do this.", author: "Joan of Arc" },
  { text: "Victory belongs to the most persevering.", author: "Napoleon Bonaparte" },
  { text: "Glory is fleeting, but obscurity is forever.", author: "Napoleon Bonaparte" },
  { text: "The supreme art of war is to subdue the enemy without fighting.", author: "Sun Tzu" },
  { text: "Appear weak when you are strong, and strong when you are weak.", author: "Sun Tzu" },
  { text: "If you know the enemy and know yourself, you need not fear the result of a hundred battles.", author: "Sun Tzu" },
  { text: "In the midst of chaos, there is also opportunity.", author: "Sun Tzu" },
  { text: "Never was anything great achieved without danger.", author: "Niccolo Machiavelli" },
  { text: "It is not titles that honor men, but men that honor titles.", author: "Niccolo Machiavelli" },
  { text: "Out of your vulnerabilities will come your strength.", author: "Sigmund Freud" },
  { text: "Knowing your own darkness is the best method for dealing with the darknesses of other people.", author: "Carl Jung" },
  { text: "Until you make the unconscious conscious, it will direct your life and you will call it fate.", author: "Carl Jung" },
  { text: "I am not what happened to me, I am what I choose to become.", author: "Carl Jung" },
  { text: "He who has a why to live for can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "And those who were seen dancing were thought to be insane by those who could not hear the music.", author: "Friedrich Nietzsche" },
  { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
  { text: "Life can only be understood backwards; but it must be lived forwards.", author: "Soren Kierkegaard" },
  { text: "The most common form of despair is not being who you are.", author: "Soren Kierkegaard" },
  { text: "All of humanity's problems stem from man's inability to sit quietly in a room alone.", author: "Blaise Pascal" },
  { text: "The heart has its reasons of which reason knows nothing.", author: "Blaise Pascal" },
  { text: "Truth is so obscure in these times, and falsehood so established, that, unless we love the truth, we cannot know it.", author: "Blaise Pascal" },
  { text: "The greatest discovery of my generation is that a human being can alter his life by altering his attitudes.", author: "William James" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "We don't laugh because we're happy; we're happy because we laugh.", author: "William James" },
  { text: "It takes courage to grow up and become who you really are.", author: "E.E. Cummings" },
  { text: "The most wasted of all days is one without laughter.", author: "E.E. Cummings" },
  { text: "Only those who will risk going too far can possibly find out how far one can go.", author: "T.S. Eliot" },
  { text: "We shall not cease from exploration, and the end of all our exploring will be to arrive where we started and know the place for the first time.", author: "T.S. Eliot" },
  { text: "What we call the beginning is often the end.", author: "T.S. Eliot" },
  { text: "The best portion of a good man's life: his little, nameless, unremembered acts of kindness and of love.", author: "William Wordsworth" },
  { text: "Fill your paper with the breathings of your heart.", author: "William Wordsworth" },
  { text: "There is no instinct like that of the heart.", author: "Lord Byron" },
  { text: "Adversity is the first path to truth.", author: "Lord Byron" },
  { text: "Time is the coin of your life. It is the only coin you have, and only you can determine how it will be spent.", author: "Carl Sandburg" },
  { text: "Nothing happens unless first we dream.", author: "Carl Sandburg" },
  { text: "Music is the universal language of mankind.", author: "Henry Wadsworth Longfellow" },
  { text: "The heights by great men reached and kept were not attained by sudden flight.", author: "Henry Wadsworth Longfellow" },
  { text: "The secret of joy in work is contained in one word: excellence.", author: "Pearl S. Buck" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { text: "Those who don't believe in magic will never find it.", author: "Roald Dahl" },
  { text: "Somewhere inside all of us is the power to change the world.", author: "Roald Dahl" },
  { text: "If you have good thoughts they will shine out of your face like sunbeams and you will always look lovely.", author: "Roald Dahl" },
  { text: "You're braver than you believe, and stronger than you seem, and smarter than you think.", author: "A.A. Milne" },
  { text: "Sometimes the smallest things take up the most room in your heart.", author: "A.A. Milne" },
  { text: "How lucky I am to have something that makes saying goodbye so hard.", author: "A.A. Milne" },
  { text: "Words are, of course, the most powerful drug used by mankind.", author: "Rudyard Kipling" },
  { text: "We have forty million reasons for failure, but not a single excuse.", author: "Rudyard Kipling" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "Always remember that you are absolutely unique. Just like everyone else.", author: "Margaret Mead" },
  { text: "I have a new philosophy. I'm only going to dread one day at a time.", author: "Charles Schulz" },
  { text: "Don't worry about the world coming to an end today. It's already tomorrow in Australia.", author: "Charles Schulz" },
  { text: "When humor goes, there goes civilization.", author: "Erma Bombeck" },
  { text: "Worry is like a rocking chair: it gives you something to do but never gets you anywhere.", author: "Erma Bombeck" },
  { text: "I refuse to join any club that would have me as a member.", author: "Groucho Marx" },
  { text: "I find television very educating. Every time somebody turns on the set, I go into the other room and read a book.", author: "Groucho Marx" },
  { text: "Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read.", author: "Groucho Marx" },
  { text: "Imagination is the only weapon in the war against reality.", author: "Lewis Carroll" },
  { text: "I can't go back to yesterday because I was a different person then.", author: "Lewis Carroll" },
  { text: "What is essential is invisible to the eye.", author: "Antoine de Saint-Exupery" },
  { text: "All grown-ups were once children, although few of them remember it.", author: "Antoine de Saint-Exupery" },
  { text: "If you want to build a ship, don't drum up people to collect wood, but rather teach them to long for the endless immensity of the sea.", author: "Antoine de Saint-Exupery" },
  { text: "A traveler without observation is a bird without wings.", author: "Saadi" },
  { text: "Right is right, even if everyone is against it; and wrong is wrong, even if everyone is for it.", author: "William Penn" },
  { text: "Time is what we want most, but what we use worst.", author: "William Penn" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "No matter what people tell you, words and ideas can change the world.", author: "Robin Williams" },
  { text: "A man of courage is also full of faith.", author: "Cicero" },
  { text: "Friendship makes prosperity more brilliant, and lightens adversity by dividing and sharing it.", author: "Cicero" },
  { text: "The life of the dead is placed in the memory of the living.", author: "Cicero" },
  { text: "If you have a garden and a library, you have everything you need.", author: "Cicero" },
  { text: "While there's life, there's hope.", author: "Cicero" },
  { text: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
  { text: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
  { text: "Silence is better than meaningless words.", author: "Pythagoras" },
  { text: "There is geometry in the humming of the strings, there is music in the spacing of the spheres.", author: "Pythagoras" },
  { text: "No man ever steps in the same river twice, for it's not the same river and he's not the same man.", author: "Heraclitus" },
  { text: "He has the most who is most content with the least.", author: "Diogenes" },
  { text: "Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.", author: "Khalil Gibran" },
  { text: "Yesterday is but today's memory, tomorrow is today's dream.", author: "Khalil Gibran" },
  { text: "Trust in dreams, for in them is hidden the gate to eternity.", author: "Khalil Gibran" },
  { text: "I wish I could show you, when you are lonely or in darkness, the astonishing light of your own being.", author: "Hafiz" },
  { text: "Don't be satisfied with stories, how things have gone with others. Unfold your own myth.", author: "Rumi" },
  { text: "Set your life on fire. Seek those who fan your flames.", author: "Rumi" },
  { text: "Why do you stay in prison when the door is so wide open?", author: "Rumi" },
  { text: "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.", author: "Saint Francis of Assisi" },
  { text: "All the darkness in the world cannot extinguish the light of a single candle.", author: "Saint Francis of Assisi" },
  { text: "For it is in giving that we receive.", author: "Saint Francis of Assisi" },
  { text: "The most important thing is to enjoy your life, to be happy. It's all that matters.", author: "Audrey Hepburn" },
  { text: "Nothing is impossible. The word itself says, I'm possible!", author: "Audrey Hepburn" },
  { text: "For beautiful eyes, look for the good in others; for beautiful lips, speak only words of kindness.", author: "Audrey Hepburn" },
  { text: "Imperfection is beauty, madness is genius, and it's better to be absolutely ridiculous than absolutely boring.", author: "Marilyn Monroe" },
  { text: "A day without laughter is a day wasted.", author: "Charlie Chaplin" },
  { text: "Nothing is permanent in this wicked world, not even our troubles.", author: "Charlie Chaplin" },
  { text: "Life is a tragedy when seen in close-up, but a comedy in long-shot.", author: "Charlie Chaplin" },
  { text: "It's kind of fun to do the impossible.", author: "Walt Disney" },
  { text: "Laughter is timeless, imagination has no age, and dreams are forever.", author: "Walt Disney" },
  { text: "Whatever you do, do it well.", author: "Walt Disney" },
  { text: "Every strike brings me closer to the next home run.", author: "Babe Ruth" },
  { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { text: "Shoot for the moon. Even if you miss, you'll land among the stars.", author: "Norman Vincent Peale" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Your attitude, not your aptitude, will determine your altitude.", author: "Zig Ziglar" },
  { text: "Lack of direction, not lack of time, is the problem.", author: "Zig Ziglar" },
  { text: "Failure is a detour, not a dead-end street.", author: "Zig Ziglar" },
  { text: "If you aim at nothing, you will hit it every time.", author: "Zig Ziglar" },
  { text: "We become what we think about.", author: "Earl Nightingale" },
  { text: "If you change the way you look at things, the things you look at change.", author: "Wayne Dyer" },
  { text: "How people treat you is their karma; how you react is yours.", author: "Wayne Dyer" },
  { text: "Doing what you love is the cornerstone of having abundance in your life.", author: "Wayne Dyer" },
  { text: "Most people do not listen with the intent to understand; they listen with the intent to reply.", author: "Stephen Covey" },
  { text: "The key is not to prioritize what's on your schedule, but to schedule your priorities.", author: "Stephen Covey" },
  { text: "Begin with the end in mind.", author: "Stephen Covey" },
  { text: "An expert is a man who has made all the mistakes which can be made, in a very narrow field.", author: "Niels Bohr" },
  { text: "The opposite of a profound truth may very well be another profound truth.", author: "Niels Bohr" },
  { text: "I would rather have questions that can't be answered than answers that can't be questioned.", author: "Richard Feynman" },
  { text: "What I cannot create, I do not understand.", author: "Richard Feynman" },
  { text: "You never change things by fighting the existing reality. To change something, build a new model that makes the existing model obsolete.", author: "Buckminster Fuller" },
  { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
  { text: "The only ones among you who will be really happy are those who have sought and found how to serve.", author: "Albert Schweitzer" },
  { text: "In everyone's life, at some time, our inner fire goes out. It is then burst into flame by an encounter with another human being.", author: "Albert Schweitzer" },
  { text: "I always wanted to be somebody, but now I realize I should have been more specific.", author: "Lily Tomlin" },
  { text: "The road to success is always under construction.", author: "Lily Tomlin" },
  { text: "In the land of the blind, the one-eyed man is king.", author: "Erasmus" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe" },
  { text: "Treat people as if they were what they ought to be, and you help them become what they are capable of being.", author: "Johann Wolfgang von Goethe" },
  { text: "A man sees in the world what he carries in his heart.", author: "Johann Wolfgang von Goethe" },
  { text: "What is not started today is never finished tomorrow.", author: "Johann Wolfgang von Goethe" },
  { text: "Just trust yourself, then you will know how to live.", author: "Johann Wolfgang von Goethe" },
  { text: "Things which matter most must never be at the mercy of things which matter least.", author: "Johann Wolfgang von Goethe" },
  { text: "'Tis better to have loved and lost than never to have loved at all.", author: "Alfred Lord Tennyson" },
  { text: "I am a part of all that I have met.", author: "Alfred Lord Tennyson" },
  { text: "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", author: "John Milton" },
  { text: "Life is so constructed, that the event does not, cannot, will not, match the expectation.", author: "Charlotte Bronte" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Bronte" },
  { text: "There is only one happiness in this life, to love and be loved.", author: "George Sand" },
  { text: "Far away there in the sunshine are my highest aspirations. I may not reach them, but I can look up and see their beauty.", author: "Louisa May Alcott" },
  { text: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott" },
  { text: "Nothing is so painful to the human mind as a great and sudden change.", author: "Mary Shelley" },
  { text: "Three things in human life are important: the first is to be kind; the second is to be kind; and the third is to be kind.", author: "Henry James" },
  { text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson" },
  { text: "Keep your fears to yourself, but share your courage with others.", author: "Robert Louis Stevenson" },
  { text: "When you want something, all the universe conspires in helping you to achieve it.", author: "Paulo Coelho" },
  { text: "One is loved because one is loved. No reason is needed for loving.", author: "Paulo Coelho" },
  { text: "There is only one thing that makes a dream impossible to achieve: the fear of failure.", author: "Paulo Coelho" },
  { text: "It's the simple things in life that are the most extraordinary.", author: "Paulo Coelho" },
  { text: "The curious paradox is that when I accept myself just as I am, then I can change.", author: "Carl Rogers" },
  { text: "When we are no longer able to change a situation, we are challenged to change ourselves.", author: "Viktor Frankl" },
  { text: "Everything can be taken from a man but one thing: the last of the human freedoms, to choose one's attitude in any given set of circumstances.", author: "Viktor Frankl" },
  { text: "Those who have a why to live, can bear with almost any how.", author: "Viktor Frankl" },
  { text: "Talent hits a target no one else can hit; genius hits a target no one else can see.", author: "Arthur Schopenhauer" },
  { text: "We forfeit three-quarters of ourselves in order to be like other people.", author: "Arthur Schopenhauer" },
  { text: "The only thing necessary for the triumph of evil is for good men to do nothing.", author: "Edmund Burke" },
  { text: "Nobody made a greater mistake than he who did nothing because he could do only a little.", author: "Edmund Burke" },
  { text: "Reading without reflecting is like eating without digesting.", author: "Edmund Burke" },
  { text: "Those who cannot remember the past are condemned to repeat it.", author: "George Santayana" },
  { text: "There is no cure for birth and death save to enjoy the interval.", author: "George Santayana" },
  { text: "The young man who has not wept is a savage, and the old man who will not laugh is a fool.", author: "George Santayana" },
  { text: "Slow and steady wins the race.", author: "Aesop" },
  { text: "United we stand, divided we fall.", author: "Aesop" },
  { text: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop" },
  { text: "Better be wise by the misfortunes of others than by your own.", author: "Aesop" },
  { text: "Friends show their love in times of trouble, not in happiness.", author: "Euripides" },
  { text: "The wisest men follow their own direction.", author: "Euripides" },
  { text: "There is a time for many words, and there is also a time for sleep.", author: "Homer" },
  { text: "Even his griefs are a joy long after to one that remembers all that he wrought and endured.", author: "Homer" },
  { text: "Fortune favors the bold.", author: "Virgil" },
  { text: "Time bears away all things.", author: "Virgil" },
  { text: "Carpe diem. Seize the day, put very little trust in tomorrow.", author: "Horace" },
  { text: "Adversity has the effect of eliciting talents which in prosperous circumstances would have lain dormant.", author: "Horace" },
  { text: "Nothing is stronger than habit.", author: "Ovid" },
  { text: "Power tends to corrupt, and absolute power corrupts absolutely.", author: "Lord Acton" },
  { text: "If everyone is thinking alike, then somebody isn't thinking.", author: "George S. Patton" },
  { text: "Accept the challenges so that you can feel the exhilaration of victory.", author: "George S. Patton" },
  { text: "Plans are nothing; planning is everything.", author: "Dwight D. Eisenhower" },
  { text: "Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.", author: "Langston Hughes" },
  { text: "When I dare to be powerful, to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.", author: "Audre Lorde" },
  { text: "We tell ourselves stories in order to live.", author: "Joan Didion" },
  { text: "How we spend our days is, of course, how we spend our lives.", author: "Annie Dillard" },
  { text: "It is good to have an end to journey toward; but it is the journey that matters, in the end.", author: "Ursula K. Le Guin" },
  { text: "The very act of trying to look ahead to discern possibilities and offer warnings is in itself an act of hope.", author: "Octavia Butler" },
  { text: "In the end, we'll all become stories.", author: "Margaret Atwood" },
  { text: "A word after a word after a word is power.", author: "Margaret Atwood" },
  { text: "Reading is to the mind what exercise is to the body.", author: "Joseph Addison" },
  { text: "I cannot remember the books I've read any more than the meals I have eaten; even so, they have made me.", author: "Ralph Waldo Emerson" },
  { text: "The world is a book, and those who do not travel read only one page.", author: "Augustine of Hippo" },
  { text: "Travel makes one modest. You see what a tiny place you occupy in the world.", author: "Gustave Flaubert" },
  { text: "A book is a dream that you hold in your hand.", author: "Neil Gaiman" },
  { text: "Where words fail, music speaks.", author: "Hans Christian Andersen" },
  { text: "Family is not an important thing. It's everything.", author: "Michael J. Fox" },
  { text: "Constant kindness can accomplish much. As the sun makes ice melt, kindness causes misunderstanding, mistrust, and hostility to evaporate.", author: "Albert Schweitzer" },
  { text: "The harder I practice, the luckier I get.", author: "Gary Player" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "There is no shortcut to anywhere worth going.", author: "Beverly Sills" },
  { text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "Persistence is the mother of all human qualities.", author: "Mahatma Gandhi" },
  { text: "Talent is cheaper than table salt. What separates the talented individual from the successful one is a lot of hard work.", author: "Stephen King" },
  { text: "We never know which lives we influence, or when, or why.", author: "Stephen King" },
  { text: "The first duty of love is to listen.", author: "Paul Tillich" },
  { text: "God grant me the serenity to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference.", author: "Reinhold Niebuhr" },
  { text: "Nine tenths of education is encouragement.", author: "Anatole France" },
  { text: "It is better to be a human being dissatisfied than a pig satisfied.", author: "John Stuart Mill" },
  { text: "Beauty in things exists in the mind which contemplates them.", author: "David Hume" },
  { text: "Reading furnishes the mind only with materials of knowledge; it is thinking that makes what we read ours.", author: "John Locke" },
  { text: "What is now proved was once only imagined.", author: "William Blake" },
  { text: "If the doors of perception were cleansed, everything would appear to man as it is, infinite.", author: "William Blake" },
  { text: "No man is an island, entire of itself; every man is a piece of the continent, a part of the main.", author: "John Donne" },
  { text: "To err is human; to forgive, divine.", author: "Alexander Pope" },
  { text: "Hope springs eternal in the human breast.", author: "Alexander Pope" },
  { text: "A little learning is a dangerous thing.", author: "Alexander Pope" },
  { text: "Knowledge is of two kinds. We know a subject ourselves, or we know where we can find information upon it.", author: "Samuel Johnson" },
  { text: "What we hope ever to do with ease, we must learn first to do with diligence.", author: "Samuel Johnson" },
  { text: "When a man is tired of London, he is tired of life.", author: "Samuel Johnson" },
  { text: "Whatever is worth doing at all, is worth doing well.", author: "Lord Chesterfield" },
  { text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand" },
  { text: "A creative man is motivated by the desire to achieve, not by the desire to beat others.", author: "Ayn Rand" },
  { text: "Don't compare yourself with anyone in this world. If you do so, you are insulting yourself.", author: "Bill Gates" },
  { text: "It's fine to celebrate success, but it is more important to heed the lessons of failure.", author: "Bill Gates" },
  { text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk" },
  { text: "If you have an apple and I have an apple and we exchange these apples then you and I will still each have one apple. But if you have an idea and I have an idea and we exchange these ideas, then each of us will have two ideas.", author: "George Bernard Shaw" },
  { text: "Be so good they can't ignore you.", author: "Steve Martin" },
  { text: "Hope is a good thing, maybe the best of things, and no good thing ever dies.", author: "Stephen King" },
  { text: "We are most alive when we're in love.", author: "John Updike" },
  { text: "The greatest happiness of life is the conviction that we are loved.", author: "Victor Hugo" },
  { text: "Life is the flower for which love is the honey.", author: "Victor Hugo" },
  { text: "He who opens a school door, closes a prison.", author: "Victor Hugo" },
  { text: "Even the darkest night will end and the sun will rise.", author: "Victor Hugo" },
  { text: "To love beauty is to see light.", author: "Victor Hugo" },
  { text: "Children are likely to live up to what you believe of them.", author: "Lady Bird Johnson" },
  { text: "Hope begins in the dark, the stubborn hope that if you just show up and try to do the right thing, the dawn will come.", author: "Anne Lamott" },
  { text: "Almost everything will work again if you unplug it for a few minutes, including you.", author: "Anne Lamott" },
  { text: "In every walk with nature, one receives far more than he seeks.", author: "John Muir" },
  { text: "The mountains are calling and I must go.", author: "John Muir" },
  { text: "Everybody needs beauty as well as bread, places to play in and pray in, where nature may heal and give strength to body and soul.", author: "John Muir" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "When you cannot get a compliment any other way, pay yourself one.", author: "Maxim Gorky" },
  { text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
  { text: "If you do what you've always done, you'll get what you've always gotten.", author: "Tony Robbins" },
  { text: "The path to success is to take massive, determined action.", author: "Tony Robbins" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "David Goggins" },
  { text: "The reason I talk to myself is because I'm the only one whose answers I accept.", author: "George Carlin" },
  { text: "Take criticism seriously, but not personally.", author: "Hillary Clinton" },
  { text: "There is something delicious about writing the first words of a story. You never quite know where they'll take you.", author: "Beatrix Potter" },
];
